### ISSUE TITLE
默认引入的zepto console报错

### ISSUE THREAD

**Issue by chasonma** [o2team/elf#11]
如题。
手动删掉elf-cli里相关zepto配置，页面直接引入cdn解决。

**Comment by booxood** [comment]
报什么错？可以贴出来看下吗？

**Comment by chasonma** [comment]
![console](http://i1.piimg.com/1949/6306101cfd3040f0.png)

**Comment by booxood** [comment]
这个时候你在控制台输入 `window.document` 试试？

**Comment by chasonma** [comment]
![呵呵](http://i1.piimg.com/1949/a715f2226e74e24d.png)

**Comment by booxood** [comment]
`window.document` 存在。。。 为什么还会报 `undefined`呢。。。奇怪了。。。

我这边没装QQ浏览器，你可以在 chrome 里试试吗

**Comment by chasonma** [comment]
firefox有出现，chrome没试过，按道理来说都是一个内核不会有区别对待的。

**Comment by booxood** [comment]
我这边在 chrome 里使用都是正常的。。。无法重现你这个问题

**Comment by xiatianAck** [comment]
我MAC chrome 也是报 zepto.js:23 
Cannot read property 'createElement' of undefined   
![image](https://cloud.githubusercontent.com/assets/9562776/23365542/6b5c7bfc-fd3e-11e6-8b95-288ace5fa025.png)
