### ISSUE TITLE
webpack全局引用zepto 应该用webpack-zepto 不然会导致zepto报错

### ISSUE THREAD

**Issue by xiatianAck** [o2team/elf#13]
本来想提交个PR 但是发现自己不会。算了

**Comment by booxood** [comment]
提交 PR 可以参考下 [Github 的文档](https://help.github.com/categories/collaborating-with-issues-and-pull-requests/)，自己创建一个项目试一次应该就知道了

不使用 webpack-zepto 也是可以的啊，你执行 `elf start` 时，有报错吗？

**Comment by xiatianAck** [comment]
有的，你试下就知道了，跟#11 一样 的情况。

**Comment by booxood** [comment]
不是浏览器 console 里的报错，是 执行 `elf start` 有什么提示信息吗？

**Comment by xiatianAck** [comment]
运行起来了，没有报错，二维码也生成了，浏览器也自动打开了。

**Comment by booxood** [comment]
1.4.0 应该修复了你们碰到了的问题

@xiatianAck @chasonma
