### ISSUE TITLE
commander 咨询

### ISSUE THREAD

**Issue by jessjava** [o2team/elf#2]
package.json中的bin ： elf为全局命令入口
在commander 中如何将elf build 指向 bin/elf-init.js文件的？（action）
谢谢

**Comment by booxood** [comment]
你是咨询 commander 的用法吗？

在 elf 文件中定义 `command` 时，只指定了 `command` 为 `build`，而没有 `action`， 如： https://github.com/o2team/elf/blob/master/bin/elf.js#L13 。当执行 `elf build` 时，`commander` 会自动的在当前目录下查找 `elf-build` 文件并执行。

在 commander 的 [README](https://github.com/tj/commander.js#git-style-sub-commands) 上也有说明。


PS：一定要有描述 program.command('build', **'build for production'**)。如果只是  program.command('build') ，如果没记错的话好像也是不行的，你可以试试。

**Comment by jessjava** [comment]
懂了。多谢
没有真正理解官方的command参数。
谢谢回复。
