### ISSUE TITLE
怎么让部分width和height不自动转rem，保留原来单位？

### ISSUE THREAD

**Issue by chasonma** [o2team/elf#25]
#### ELF 版本
v1.8.0
#### 运行环境
windows
#### 报错信息
无

**Comment by booxood** [comment]
转 rem 是基于 postcss-plugin-px2rem 实现的，通过配置项 [px2remOptions](https://github.com/o2team/elf/blob/master/doc/CONFIGURATION.md#px2remoptions) 进行设置，对于某些不想转 rem 的地方：
- 可以把 px 修改为大写的 PX
- 配置 selectorBlackList ，默认为：[/.ignore-rem/]，如果 class name 类似 xxx-ignore-rem 就不会转
- 还可以 propWhiteList、 propBlackList 进行控制
- minPixelValue 也可以控制最小的转换值，这个现在默认是0，后面准备改为2了

**Comment by booxood** [comment]
问题就先关闭了哈
