### ISSUE TITLE
请问支持babel编译？

### ISSUE THREAD

**Issue by Jerrodly** [o2team/elf#27]

**Comment by booxood** [comment]
默认安装的是不支持的。但可以扩展 loader 支持，参考这个模板 [elf-templates/react](https://github.com/elf-templates/react/blob/master/.elf.config.js#L35)。

**Comment by vxhly** [comment]
还是比较喜欢es6的语法，研究一下怎么配置吧，希望作者也能早一点支持babel编译，具体可以参考 vue-cli的做法，然后如果能有构建属于自己的模板一个文档那就更好了

**Comment by booxood** [comment]
@JerrodNoliita @vxhly 新增了一个模板 [elf-templates/babel](https://github.com/elf-templates/babel) 可以直接使用 es6 语法。

```sh
elf init -t babel 
```


@vxhly 你可以基于这个项目修改创建属于你自己的模板。

**Comment by hzg4027** [comment]
@booxood 用这个模板 build 报错
ERROR in js/bundle.js from UglifyJs

**Comment by vxhly** [comment]
@hzg4027 初步判断是 Zepto.js这个的问题，把默认给的例子改掉就行
@booxood 其实个人不推荐 Zepto.js，jQuery不是用的比较广泛

**Comment by vxhly** [comment]
@booxood 好像凡是涉及到类都会报错啊

Hash: 6daac46febf43d4e8198
Version: webpack 3.3.0
Time: 5963ms
        Asset     Size  Chunks                    Chunk Names
img/babel.png   274 kB          [emitted]  [big]
 js/bundle.js  5.28 kB       0  [emitted]         main
  css/app.css  2.62 kB       0  [emitted]         main
   index.html  3.19 kB          [emitted]

ERROR in js/bundle.js from UglifyJs
Unexpected token: name (StdInfo) [js/bundle.js:129,6]

  Build finished.

**Comment by booxood** [comment]
@hzg4027 @vxhly 使用命令
```
elf init -t elf-templates/babel
```
初始化项目，这样 build 就不会报错了。

其实主要是要在配置文件中增加
```
  rules: [{
    test: /\.js?$/,
    exclude: /node_modules/,
    use: [{
      loader: 'babel-loader',
      options: {
        cacheDirectory: true,
        babelrc: true,
      }
    }]
  }],
```

**Comment by vxhly** [comment]
OK 解决了
