### ISSUE TITLE
zepto打包

### ISSUE THREAD

**Issue by jessjava** [o2team/elf#3]
使用elf init -t base 之后 zepto 默认是没有加载在页面的。是不是程序有问题？
webpack.base.js 中 webpack 插件配置的地方：
new webpack.ProvidePlugin({
      $: zeptoPath,
      Zepto: zeptoPath,
      'window.Zepto': zeptoPath
    })

**Comment by booxood** [comment]
默认是加载的

你在控制台输入 `Zepto` 是 `undefined` 吗？

**Comment by jessjava** [comment]
got it
