### ISSUE TITLE
模版无法下载，404了

### ISSUE THREAD

**Issue by Johansenlbw** [o2team/elf#32]
#### 报错信息
模版下载404，不知道是啥原因

**Comment by booxood** [comment]
@Johansenlbw 哪个模板？

**Comment by Johansenlbw** [comment]
Failed to download repo elf-templates/panorama: Response code 404 (Not Found)

**Comment by booxood** [comment]
@Johansenlbw 模板 https://github.com/elf-templates/panorama 是存在的啊，是不是你的网络问题？

**Comment by Johansenlbw** [comment]
命令行elf init -t 好像不好使，我还是git clone 吧   🙏，谢谢
