### ISSUE TITLE
Linux 安装报依赖错误

### ISSUE THREAD

**Issue by bb36241189** [o2team/elf#38]
#### ELF 版本
安装的时候，没有输入版本号

#### 运行环境
Ubuntu 

#### 报错信息
SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by booxood** [comment]
这个是告警，不影响。还有其他报错吗？
