### ISSUE TITLE
webpack咨询

### ISSUE THREAD

**Issue by jessjava** [o2team/elf#4]
不好意思，又来打扰您了
webpack.base.js 中 webpack的 resolve 的 alias的配置如下：
alias:{ src: resolveApp('src') }
这里不明白在elf 中如何使用和表现的？src 为绝对路径吗？使用时机是什么时候？

还有个问题，现在在 html 页面写 img 标签时src中如果引入本地文件（相对路径）
`<img src="./img/html5-logo.png">`
start 或者 build 都会报错。
报的是/node_modules/pngquant-bin/vendor/pngquant失败。麻烦您给看看？
以下是错误信息：
`
ERROR in ./src/img/html5-logo.png 
Module build failed: Error: spawn /usr/local/lib/node_modules/elf-cli/node_modules/pngquant-bin/vendor/pngquant ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./src/index.html 1:1133-1164
`

帮帮新手，谢谢

**Comment by booxood** [comment]
指定 `alias:{ src: resolveApp('src') }` 后，在代码中可以通过绝对地址来引入文件：例如 `require('src/js/main.js')` ，而不用考虑当前文件所处于的目录。

**Comment by booxood** [comment]
后面这个报错应该是 `pngquant-bin` 这包安装出错了，重新安装一下，或者把 `ELF` 整个重装一下试试。

**Comment by jessjava** [comment]
重装了几次。都不行，最后还是根据PHANTOMJS_CDNURL=https://npm.taobao.org/mirrors/phantomjs/ 这个设置安装ok，然后pngquant就 ok 了。
我想问下这个怎么验证某些模块没装好呢？感觉挺重的。

**Comment by booxood** [comment]
看安装完成后的提示信息来吧，有模块没安装成功会报错的。

因为依赖很多 `*-loader `，为了保证顺利安装，强烈建议使用这条命令
`
SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ PHANTOMJS_CDNURL=https://npm.taobao.org/mirrors/phantomjs/ npm install -g elf-cli --registry=https://registry.npm.taobao.org
`
来安装。

**Comment by aispin** [comment]
@jessjava 鉴于国情，建议将在`.bashrc`或`.zshrc`里面加入`SASS_BINARY_SITE `和`PHANTOMJS_CDNURL `的配置，除了`elf`，其实很多别的包都依赖它们的。具体的做法是在文件里面加入以下内容，参考下：

```
export ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"
export PHANTOMJS_CDNURL="https://npm.taobao.org/dist/phantomjs"
export SASS_BINARY_SITE = "https://npm.taobao.org/mirrors/node-sass/"
```



@booxood `elf`默认可以用`stylus`，轻量，而且语法能兼容`sass`

**Comment by booxood** [comment]
@mamboer 现在是 `stylus`、`sass`、`less` 默认都支持

**Comment by jessjava** [comment]
@booxood @mamboer 多谢
