### ISSUE TITLE
ico图标文件不能够引入

### ISSUE THREAD

**Issue by D1N910** [o2team/elf#40]
#### ELF 版本
v1.9.1
#### 运行环境
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
#### 报错信息
无

如题orz

尝试改webpack配置，不让过有点无从下手。。。

**Comment by booxood** [comment]
默认没有对 ico 文件进行处理。
可以参考 https://github.com/elf-templates/react 的配置，增加 rules

```
{
  test: /\.ico$/,
  include: '...',
  use: [{
    loader: 'url-loader', // or file-loader
    options: {
    }
  }]
}
```

**Comment by D1N910** [comment]
我失败了
如下配置后，并不能够引入icon文件

.elf.config.js配置：
```
  // 该目录下的的图片默认被转成 base64
  imgToBase64Dir: /src\/img-base64/,
  externals: {},
  rules: [
    {
      test: /\.ico$/,
      use: [{
        loader: 'url-loader', // or file-loader
        options: {
        }
      }]
    }
  ],
  /**
   * html-webpack-plugin 默认配置
   * 详细描述参考：https://github.com/ampedandwired/html-webpack-plugin
   */
```

文件路径
![](http://ww1.sinaimg.cn/large/006ES7aSgy1fxuolnk1cqj30h20psmz3.jpg)

使用方式
`  <link rel="shortcut icon" href="./img/public/favicon.ico" type="image/vnd.microsoft.icon">`

**Comment by booxood** [comment]
在你的 js 代码中加一句 `require('../xxx/public/favicon.ico')` 引用一下你想加载的文件

**Comment by D1N910** [comment]
我已尝试加入require('../xxx/public/favicon.ico')，发现之前配置的wepack语句是起效的，loader乱填就会报错。 

但是还是不能起效果

**Comment by booxood** [comment]
会报什么错？

你期望效果是怎么样的？

**Comment by D1N910** [comment]
我期望的效果是在chrome浏览器上能够显示网页的ico
----------- 
loader乱填就会报错-指填写非url-loader的时候报错，说明我这个配置是有用的，至少没写错，改回去就不会报错了。  

现在我已经配置好了引入ico的webpack，也在对应的js文件内引入了ico，还是不能够显示。

**Comment by D1N910** [comment]
<del>好极了，现在有了明了的报错
`ERROR in ./src/img/public/favicon.ico
Module parse failed: /Users/Pengjiangao/hhp-mobile-website/src/img/public/favicon.ico Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)`</del>


<del>我尝试换下别的加载器

<del>另外【编辑</del>
<del>我时下用的loader</del>
<del>`  rules: [
    {
      test: /\.(icon)$/,
      use: [{
        loader: 'url-loader?limit=8192&name=img/[hash:8].[name].[ext]',
        options: {
        }
      }]
    }
  ],`</del>

好吧，原来是因为我的匹配没有写对，刚刚是icon，所以才有这个报错，还是不能显示ico

**Comment by booxood** [comment]
@D1N910 试了下，这里有个坑，url-loader 对 ico 默认采用 base64 方式引入 。。[看这里](https://github.com/webpack/webpack/issues/1336) 
所以，如果是用 url-loader 的话，设置一下 limit， 或者直接用 file-loader。
```
  rules: [
    {
      test: /\.ico$/,
      use: [{
        loader: 'url-loader', // or file-loader
        options: {
          limit: 1,
          name: 'img/[name].[ext]'
        }
      }]
    }
  ],
```
name 指定了 build 后文件的输出路径，`name: 'img/[name].[ext]'`，则用 `.img/xxx.ico` 引入。
如果是想 
```
<link rel="shortcut icon" href="./img/public/favicon.ico" type="image/vnd.microsoft.icon">
```
则设置 name: 'img/public/[name].[ext]'

**Comment by booxood** [comment]
可以从控制台看输出的文件
![image](https://user-images.githubusercontent.com/2151410/49488295-f41f6280-f880-11e8-8205-3a35996fb8fe.png)

**Comment by D1N910** [comment]
@booxood hey 大佬，用这种办法，我能够打包ico。
![](http://ww1.sinaimg.cn/large/006ES7aSgy1fxvv2jbm5pj315q0uamz8.jpg)
但是依然没有办法在chrome里看到ico。
![](http://ww1.sinaimg.cn/large/006ES7aSgy1fxvv33huuoj311a0eu781.jpg)
在Safari可以。
![](http://ww1.sinaimg.cn/large/006ES7aSgy1fxvv533hpjj30eg02a74f.jpg)
我留意到一个细节，就是这边的打包配置，不能够修改html的head里的内容。

现在我使用[一个生成各种情况下的ico](https://realfavicongenerator.net/)，可以通过手动的方式加上去，这样就可以看到了。暂时先这样吧。

之前我做的项目直接操作webpack的配置（事实上我也知道这边修改.elf.config.js）也相当于直接操作webpack，用img-loader就可以引用到ico😢

**Comment by booxood** [comment]
> 但是依然没有办法在chrome里看到ico

是不是因为缓存

**Comment by D1N910** [comment]
@booxood 我日常开了disable 缓存orz，现在还遇到了雪碧图的坑，回头看看怎么优化下，现在着急项目上线

**Comment by D1N910** [comment]
@booxood 
hey亲爱的booxood，不知道如何感谢你们这个开源项目， 它支撑了我在4天内完成了一套移动端的官网【当然其中有一些时间是花在了协调和联调上，比如给中文图片全部命名成英文——切图仔123】
如果你愿意的话，你可以访问下面的这个官网来查看这个项目对我的帮助做出来的产品。
[汇合派移动端](http://www.huihedian.com/mobile/)

有一个关于雪碧图的bug，我在整理后会提个issue【滑稽】

**Comment by booxood** [comment]
@D1N910 不错。帮助开源项目进步就是感谢。
