### ISSUE TITLE
Build 是编译sass-loader报错

### ISSUE THREAD

**Issue by WalterZou** [o2team/elf#6]
在开发模式下即`npm run start`时，可以正常编译热更新。
但是`npm run build`就报下面的错误： 
![image](https://cloud.githubusercontent.com/assets/3727208/22018208/a8e1ff7c-dce8-11e6-9b35-b5923ba19743.png)

**Comment by booxood** [comment]
使用的 elf 的版本是多少？

尝试修改 `.elf.config.js` 把 `enableImageMin` 设置为 `false` 试下是不是就不报错了？

**Comment by WalterZou** [comment]
@booxood 
elf 版本为`1.3.5`
把 `enableImageMin` 设置为 `false`可以避免编译出错

**Comment by booxood** [comment]
那应该是 `image-webpack-loader` 这个库安装没成功，导致压缩图片时出错。重新安装这个库试试。

如果一直不成功，就关闭图片压缩功能吧，等 `build` 好之后用其他工具压缩图。

**Comment by WalterZou** [comment]
@booxood 嗯，感谢。
目前又有新的问题，zepto报错`Cannot read property 'createElement' of undefined`：
![image](https://cloud.githubusercontent.com/assets/3727208/22047920/e02d8b46-dd64-11e6-8980-62d943c1dc6a.png)

我自己Google下解决方法，对比目前elf-cli的webpack配置，目前的配置应该是不会存在这个问题的...
昨天使用时还没有这个问题，今天reinstall了elf-cli就出现这个问题了...

**Comment by booxood** [comment]
运行的项目是直接初始化的吗？

还有没有更多信息？

**Comment by WalterZou** [comment]
@booxood 项目是初始化的`switcher template`，之前开发一直没有报这个zepto的错误，今天早晨reinstall `elf-cli`再运行`elf start`就出现这个报错了。

**Comment by WalterZou** [comment]
@booxood 是否考虑把webpack的配置下放到template，这样方便个性调整和debug，不需要去修改elf的源码

**Comment by booxood** [comment]
`reinstall elf-cli` 是怎么 `reinstall` 的？

**Comment by WalterZou** [comment]
@booxood `npm uninstall -g elf-cli` ->`npm install -g elf-cli` 我已经使用taobao registry。我现在再重新安装下试试，`node-sass`安装也是个坑，一直导致安装失败...

**Comment by booxood** [comment]
> 是否考虑把webpack的配置下放到template

现阶段不考虑直接把 webpack 的配置文件暴露出来。尽量通过配置项的方式来满足需求。

其实一开始的时候就考虑过要不要提类似 `create-react-app` 那样的 `inject` 的命令，后面想想，如果现在就提供这个功能，那在使用的过程中可能遇到一些目前配置项无法处理的需求时就直接 `inject`，就不会关注如何优化配置项，思考是否有变通办法可以实现。

所以，目前不提供，以后也许（应该）会提供。

**Comment by booxood** [comment]
使用 `SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ PHANTOMJS_CDNURL=https://npm.taobao.org/mirrors/phantomjs/ npm install -g elf-cli --registry=https://registry.npm.taobao.org
`
这条命令安装啦

**Comment by WalterZou** [comment]
@booxood 开发环境不是Mac（捂脸），是Windows（逃）...
使用`npm install -g elf-cli --SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ ` 貌似也不行（更正：是可以的...）。Ps: phantomjs 已经加入path，registry已经是taobao registry ；`--SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/` 参数，在单独安装`node-sass`是有效的。

**Comment by WalterZou** [comment]
zepto报错确实是`elf-cli`安装不完全的问题。推荐在Windows下使用下面命令安装：
```
npm install -g elf-cli --PHANTOMJS_CDNURL=https://npm.taobao.org/mirrors/phantomjs/ --SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ --registry=https://registry.npm.taobao.org
```

**Comment by booxood** [comment]
你是在 `cmd.exe` 上执行吗？

我记得在 Windows 的 `git shell` 里试过我发的那条命令是可以的。

**Comment by WalterZou** [comment]
`cmd` 或者 `powershell`，Windows下多数编辑器的terminal还是使用的这两者，所以还没在`git shell`测试，`git shell` 是基于`mintty`，应该可以。

**Comment by booxood** [comment]
已把你这种 npm 设置环境变量的安装方式更新到 readme 了
